services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shopping_db
    ports:
      - "5432:5432"
    volumes:
      # This automatically runs our SQL on startup
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d shopping_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend-service:
    # Adding the specific tag here
    image: mattvarghesedocker/k3s-cicd-play-backend:v4
    build: ./backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      # Note the host change: inside the docker network, the db service is found at 'db'
      DATABASE_URL: postgres://user:password@db:5432/shopping_db
      # This is the "iss" claim inside the token (must be localhost for the browser)
      KEYCLOAK_ISSUER_URL: http://localhost:8080/realms/shopping-realm
      # ADD THIS: The actual internal path to the certs
      KEYCLOAK_JWKS_URL: http://keycloak:8080/realms/shopping-realm/protocol/openid-connect/certs
      # The physical address the backend uses to talk to Keycloak
      KEYCLOAK_INTERNAL_URL: http://keycloak:8080
      # Keycloack client info
      KEYCLOAK_CLIENT_ID: shopping-app
    depends_on:
      db:
        condition: service_healthy
      keycloak:
        condition: service_healthy

  frontend:
    # Adding the specific tag here
    image: mattvarghesedocker/k3s-cicd-play-frontend:v2
    build: ./frontend
    restart: always
    ports:
      - "3001:80" # Maps Nginx port 80 to your familiar 3001
    depends_on:
      - backend-service

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev --import-realm
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: "false"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak_db
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: password
      KC_HEALTH_ENABLED: "true"
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import  # This brings in the shopping-realm.json file
    healthcheck:
      # This checks if the port 8080 is accepting connections
      test: ["CMD-SHELL", "cat < /dev/null > /dev/tcp/127.0.0.1/8080"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s # Gives Java time to warm up before failing
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
