services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shopping_db
    ports:
      - "5432:5432"
    volumes:
      # This automatically runs our SQL on startup
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  backend-service:
    # Adding the specific tag here
    image: mattvarghesedocker/k3s-cicd-play-backend:v3
    build: ./backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      # Note the host change: inside the docker network, the db service is found at 'db'
      DATABASE_URL: postgres://user:password@db:5432/shopping_db
    depends_on:
      - db

  frontend:
    # Adding the specific tag here
    image: mattvarghesedocker/k3s-cicd-play-frontend:v2
    build: ./frontend
    restart: always
    ports:
      - "3001:80" # Maps Nginx port 80 to your familiar 3001
    depends_on:
      - backend-service

volumes:
  postgres_data:
