apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:latest
        args: ["start", "--http-enabled=true", "--import-realm"]  #--http-enabled=true is bad for production
        env:
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          value: "admin"
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          value: "admin"
        - name: KC_DB
          value: "postgres"
        - name: KC_DB_URL
          value: "jdbc:postgresql://shopping-db:5432/shopping_db"
        - name: KC_DB_USERNAME
          value: "postgres"
        - name: KC_DB_PASSWORD
          value: "password"
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: KC_HEALTH_ENABLED
          value: "true"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: realm-import-vol
          mountPath: /opt/keycloak/data/import
          readOnly: true
      volumes:
      - name: realm-import-vol
        configMap:
          name: keycloak-realm-import
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 8080       # This maps to your host port 8080
      targetPort: 8080 # This is the port inside the container
  type: LoadBalancer   # The "Magic" that keeps your .env consistent