apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k3s-cicd-play
labels:
  - pairs:
      project: shopping-list

resources:
  - db-deploy.yaml
  - backend-deploy.yaml
  - frontend-deploy.yaml
  - keycloak-deploy.yaml
