apiVersion: v1
kind: Namespace
metadata:
  name: k10s-gui
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k10s-viewer
  namespace: k10s-gui
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k10s-view-role
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "namespaces", "services", "replicationcontrollers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "statefulsets", "replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k10s-view-binding
subjects:
  - kind: ServiceAccount
    name: k10s-viewer
    namespace: k10s-gui
roleRef:
  kind: ClusterRole
  name: k10s-view-role
  apiGroup: rbac.authorization.k8s.io
