apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k10s-gui
labels:
  - pairs:
      project: k10s-monitoring

resources:
  - k10s-infra.yaml
  - k10s-deploy.yaml

configMapGenerator:
  - name: k10s-nginx-conf
    files:
      - default.conf=nginx.conf

generatorOptions:
  disableNameSuffixHash: true